require_relative 'terms/ident'
require_relative 'terms/string'
require_relative 'terms/number'
require_relative 'terms/function'
require_relative 'terms/uri'
require_relative 'terms/rgb'
require_relative 'terms/hash'
